# Generated by Django 4.1 on 2022-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
